### ISSUE TITLE
iOS Beta版デザインチェックリスト

### ISSUE THREAD

**Issue by Rhime-design** [ryuta46/raccoonwallet-ios#1]
Androidのほうに建てたやつを移植しました。追加もあります。
それぞれどのぐらいやり取りする必要があるか不明なため、とりあえずリストにしてずらずらと書いておきます。
もし複雑になりそうな箇所があるときは別個でissueを建ててもらえればと思います。
完了したやつはチェックします。だれでもチェックできるんでしたっけかな？
できる人がチェックお願いします。

<br>
<hr>
<br>
▼UI/UX

- [x] Android版みたいにHOMEをスワイプでｼｭｯｼｭｯっと移動したい。→**なしでOKですね**
- [x] 左端→→スワイプでドロワーを出したい。

- [x] トランザクション画面でのスクロール時に、heroimageが隠れない
- [x] Android版もですが、Hello NEMber、やっぱ別に要らないかな…いや…どうなんだろう
- [x] Android版もですが、ウォレットバーのウォレットボタンのタップ反応範囲がシビアなので、ボタンより一回り大きくしたい。
- [x] アドレスコピー（他）のトーストがボトムナビに被るのをどうにかしたい👀
ボトムナビはドロワーを除けば最上位Layerに位置していて、他の要素侵食されないでほしい。

- [x] HOMEの残高やトランザクションの小窓が表示のつどローディングされるのを、初回で取得した後、キャッシュを使ってイベント時やユーザーの下スワイプが入力されたとき以外は静的に表示しておいてほしい。
- [x] ローディングが要素ごとに表示される部分に関して。
↑に書いた挙動を前提にしていますが、
iOS標準（たぶん）のちっこいローディングを、オーバーレイで画面中央に表示する程度で良いと思いました。
![2018-09-27_09h39_28](https://user-images.githubusercontent.com/34479640/46116896-3ef57c00-c239-11e8-9044-6b29ac30fa98.png)

<br>

🖊2018 10/1追記

- [x] レイヤー構造的に言えば、ウォレットバーをツールバーの下にして、ドロップシャドウをかけたい。（Android版、もしくは下記添付iPhoneモックを参照ください。）

- [x] ホームのカード内のマージンの整え作業。（Android版、もしくは下記添付iPhoneモックを参照ください。）

- [x] トーストの表示時間が少し長いかもしれない⌛️
5s→3sに変更できますか？

<br>

### ヒューマンインタフェースデザインに基づく調整

![2018-10-01_13h00_12](https://user-images.githubusercontent.com/34479640/46269147-1394c900-c57a-11e8-93b7-33f5f54fef8e.png)
<br>
<div style="text-align: center;">↑理想はHPにもあるこの感じ。（margin、Navigationbar）</div>
<br>

- [x] およびiOSヒューマンインタフェースデザインに基づいたナビゲーションバーにしたい。

Statusbarは、Androidではカラーが置かれていたりもしますが、個人的に色々調査すると、**iOSの場合大体はStatusbarとNavbarが統一されたカラーリングで一体化されているので**、違和感をなくすためにも統一したいなと思っています。
w375のときに、h64のボックスで、StatusbarとNavigationbarの上部のエリアを定義する。
![2018-10-01_13h35_36](https://user-images.githubusercontent.com/34479640/46269900-22ca4580-c57f-11e8-9340-2440ad638ad0.png)

▼不具合・改善

- [x] Tx取得やQR読み込み、SEND完了などのローディングがちょっと遅い？→✅🎉！
<br>

### 送金確定
- [x] 指紋認証で送金できない？
- [x] 送金確定時にPINを使う際のボタンがない。
![2018-10-01_13h47_16](https://user-images.githubusercontent.com/34479640/46270091-8d2fb580-c580-11e8-8985-c9275d654b4c.png)

> →最新版でも確認したのですが、指紋認証で送金できず。端末が化石なのであれですが、TouchIDは動作しているデバイスなので、そこは原因から切り離せると思っています。
**→動作確認できました。**

それで、Androidでは指紋認証を遷移先UIのままで待機できるようにしていたのですが、**iOSではそれができないとのことなので、**

1. **下部の指紋認証待機UIを取り除いて、SENDボタンを設置する**→押されたら、上に添付したような**Appstoreの指紋認証のようなコンポーネント**を使えればそれを下からｼｭｯっと表示させる。→認証で送金
2. 上記仕様に変更した上で、PINを使う場合のことを考えて、Android版にあるようなPIN画面表示ボタンを設置する。

としたいかなと思っています。SENDボタンのUIについては、別issueで建てます。

> それで指紋認証のUIなんですが、これはAppleのほうでAPI的に呼び出せる定形のコンポーネントとかってありますか？
> Androidでもこんなやり取りありましたが、あちらは特にそういうのはなくて、各々独自実装でやってるみたいですね👀
→**iOSはちゃんとしたダイアログが出せるみたいですね！確認できました。ありがとうございます。**

<br>
<br>

🖊随時追記します。

**Comment by ryuta46** [comment]
Hello NEMber のところは、とりあえず今は変えないということになったので、チェック入れました。
一旦クローズします。また修正した方が良いとこ出てきたら別途 issue 立てるようにしましょう。
